### ISSUE TITLE
program test error i thing.

### ISSUE THREAD

**Issue by yannick101693** [learn-co-curriculum/javascript-intro-to-functions-lab#69] opened 2017-12-17 04:11 UTC
i was doing the program test i changed and save something but now instead of 7 test its only showing me 6 test when i try to run the program.

**Comment by drakeltheryuujin** [comment] 2018-07-24 21:50
Hi there,

It looks like you've moved past this lesson, so I will close this for now.If you need additional assistance, try discussing your issue via the Ask a Question tool.

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Closed as completed by drakeltheryuujin** 2018-07-24 21:50 UTC
Labels: Product
