### ISSUE TITLE
Intro to Functions Lab

### ISSUE THREAD

**Issue by ranishah76** [learn-co-curriculum/javascript-intro-to-functions-lab#68] opened 2017-11-06 13:58 UTC
Hi, 

Failing to understand what reference error I hve made.

**Comment by drakeltheryuujin** [comment] 2018-07-24 21:48
Hi there,

It looks like you've already resolved the issue and moved onto other lessons, so I will close this for now. If you need additional assistance, try discussing your issue via the Ask a Question tool. 

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Closed as completed by drakeltheryuujin** 2018-07-24 21:48 UTC
Labels: Test
